{% set name = "mdformat-tables" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat_tables-{{ version }}.tar.gz
  sha256: a57db1ac17c4a125da794ef45539904bb8a9592e80557d525e1f169c96daa2c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - mdformat <0.8.0,>=0.7.5
    - wcwidth >=0.2.13

test:
  imports:
    - mdformat_tables
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/executablebooks/mdformat-tables
  summary: An mdformat plugin for rendering tables.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
